### ISSUE TITLE
GridFS and save files

### ISSUE THREAD

**Issue by stojankukrika** [jenssegers/laravel-mongodb#826]
Hi,
I use this https://github.com/jenssegers/laravel-mongodb/issues/262#issuecomment-50905352 for save file into database. But how to get that file and able user to download it?

**Comment by jmikola** [comment]
Note that https://github.com/jenssegers/laravel-mongodb/issues/262#issuecomment-50905352 appears to be a request for a possible GridFS API to be implemented by this library. I don't believe it is a functional example.

To cross-reference with my reply in https://github.com/jenssegers/laravel-mongodb/issues/838#issuecomment-228841563:

> Version 3.0 of this library appears to wrap [mongodb/mongo-php-library](https://github.com/mongodb/mongo-php-library), which does not implement GridFS. Support for GridFS will show up in 1.1.0 (see: [PHPLIB-114](https://jira.mongodb.org/browse/PHPLIB-114)); however, it's API will differ significantly from the [legacy driver's GridFS API](http://php.net/mongogridfs).

I assume that anyone using GridFS with this library is actually working with the legacy driver's [MongoGridFS](http://php.net/mongogridfs) class directly.

**Comment by JoeyHoutenbos** [comment]
This should work in MongoDB PHP Library version 1.1.x:
```
DB::getMongoDB()->selectGridFSBucket();
```

This will return an instance of `MongoDB\GridFS\Bucket`. Next steps can be followed here: https://docs.mongodb.com/php-library/master/tutorial/gridfs/

**Comment by bisht2050** [comment]
GridFS is now supported! 
Follow the docs to learn how to use GridFS : https://www.mongodb.com/docs/drivers/php/laravel-mongodb/current/filesystems/
